# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Xposed_models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=225)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(max_length=225)),
                ('sex', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('instagram_profile', models.CharField(max_length=225)),
                ('height', models.IntegerField()),
                ('bust', models.IntegerField()),
                ('waist', models.IntegerField()),
                ('hips', models.IntegerField()),
                ('shoes_size', models.IntegerField()),
                ('hair_color', models.CharField(max_length=10)),
                ('eyes_color', models.CharField(max_length=10)),
                ('portrait_photo', models.ImageField(upload_to='')),
                ('profile_photo', models.ImageField(upload_to='')),
                ('full_figure_photo', models.ImageField(upload_to='')),
                ('verification', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='pictures',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xposed.Xposed_models'),
        ),
    ]
