# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xposed', '0002_auto_20180614_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xposed_models',
            name='sex',
            field=models.CharField(default='male', max_length=10),
            preserve_default=False,
        ),
    ]
