# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xposed', '0004_auto_20180619_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
